# Generated by Django 3.0.4 on 2020-05-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200506_0347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
